---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: colors
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: colors
    spec:
      containers:
      - name: colors
        image: reveller/colors:1.3
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 5000
